### ISSUE TITLE
打个Nuget包到官方站嘛

### ISSUE THREAD

**Issue by xxdqr** [6tail/lunar-csharp#3]
打个包，引用起来方便点

**Comment by 6tail** [comment]
我用的vs2005貌似不支持Nuget。

**Comment by xxdqr** [comment]
安装dotnet sdk，直接用命令打包，不需要vs


 

-------- 原始邮件 --------
发件人：6tail ***@***.***>
时间：2021年10月21日 21:41
收件人：6tail/lunar-csharp ***@***.***>
抄送：xxdqr ***@***.***>,Author ***@***.***>
主题：Re: [6tail/lunar-csharp] 打个Nuget包到官方站嘛 (#3)

**Comment by 6tail** [comment]
@xxdqr 我试过了，打不起，报一堆错。

**Comment by 6tail** [comment]
有了：https://www.nuget.org/packages/lunar-csharp
