### ISSUE TITLE
不支持.NET Framework 4.5吗？在4.5上面没法使用啊

### ISSUE THREAD

**Issue by huaxuanHan** [6tail/lunar-csharp#5]

**Comment by huaxuanHan** [comment]
升级到.NET Framework 4.6.1可以使用了，但是这么写报错Lunar lunar = solar.getLunar();
Lunar 是命名空间不是类型

**Comment by 6tail** [comment]
肯定支持啊，新版本已经完全按.net开发习惯了，命名空间为Lunar：
`using Lunar;`

`var solar = new Solar(1986, 5, 29);`
`var lunar = solar.Lunar;`
